import type { TransportStop, TransportRoute } from '@/lib/types/transport'

// Bundled fallback data (generated by scripts/fetch-osm-transport.mjs)
import fallbackStopsData from '@/assets/data/transport-stops.json'
import fallbackRoutesData from '@/assets/data/transport-routes.json'

export function getTransportStops(): TransportStop[] {
  return (fallbackStopsData.stops as TransportStop[]) || []
}

export function getTransportRoutes(): TransportRoute[] {
  return (fallbackRoutesData.routes as TransportRoute[]) || []
}
