import { supabase } from '@/lib/supabase/client'
import type { TransportStop, TransportRoute } from '@/lib/types/transport'

// Bundled fallback data (generated by scripts/fetch-osm-transport.mjs)
import fallbackStopsData from '@/assets/data/transport-stops.json'
import fallbackRoutesData from '@/assets/data/transport-routes.json'

export async function fetchTransportStops(): Promise<TransportStop[]> {
  try {
    const { data, error } = await supabase
      .from('transport_stops')
      .select('osm_id, name, latitude, longitude, stop_type')
      .limit(5000)

    if (!error && data && data.length > 0) {
      return data.map((s) => ({
        osm_id: s.osm_id,
        name: s.name,
        lat: s.latitude,
        lng: s.longitude,
        type: s.stop_type,
      }))
    }
  } catch {
    // Fall through to bundled data
  }

  return fallbackStopsData.stops as TransportStop[]
}

export async function fetchTransportRoutes(): Promise<TransportRoute[]> {
  try {
    const { data, error } = await supabase
      .from('transport_routes')
      .select('osm_id, name, ref, route_from, route_to, route_type, coordinates')
      .limit(1000)

    if (!error && data && data.length > 0) {
      return data.map((r) => {
        // Supabase may return jsonb as string or parsed object
        const coords = typeof r.coordinates === 'string'
          ? JSON.parse(r.coordinates)
          : r.coordinates
        return {
          osm_id: r.osm_id,
          name: r.name,
          ref: r.ref,
          from: r.route_from,
          to: r.route_to,
          type: r.route_type,
          coordinates: coords,
        }
      })
    }
  } catch {
    // Fall through to bundled data
  }

  return fallbackRoutesData.routes as TransportRoute[]
}
