import { supabase } from '@/lib/supabase/client'
import type { TransportStop, TransportRoute } from '@/lib/types/transport'

// Bundled fallback data (generated by scripts/fetch-osm-transport.mjs)
import fallbackStopsData from '@/assets/data/transport-stops.json'
import fallbackRoutesData from '@/assets/data/transport-routes.json'

export async function fetchTransportStops(): Promise<TransportStop[]> {
  try {
    const { data, error } = await supabase
      .from('transport_stops')
      .select('osm_id, name, latitude, longitude, stop_type')

    if (!error && data && data.length > 0) {
      return data.map((s) => ({
        osm_id: s.osm_id,
        name: s.name,
        lat: s.latitude,
        lng: s.longitude,
        type: s.stop_type,
      }))
    }
  } catch {
    // Fall through to bundled data
  }

  return fallbackStopsData.stops as TransportStop[]
}

export async function fetchTransportRoutes(): Promise<TransportRoute[]> {
  try {
    const { data, error } = await supabase
      .from('transport_routes')
      .select('osm_id, name, ref, route_from, route_to, route_type, coordinates')

    if (!error && data && data.length > 0) {
      return data.map((r) => ({
        osm_id: r.osm_id,
        name: r.name,
        ref: r.ref,
        from: r.route_from,
        to: r.route_to,
        type: r.route_type,
        coordinates: r.coordinates,
      }))
    }
  } catch {
    // Fall through to bundled data
  }

  return fallbackRoutesData.routes as TransportRoute[]
}
